name: build book

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Install Playwright
        run: bunx playwright install

      - name: build book
        run: bun run build --press-ready

      - uses: actions/upload-artifact@v3
        with:
          name: Artifacts
          path: ./*.pdf
          retention-days: 3
