name: build book

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Install IBM Plex Sans
        run: |
          sudo apt-get update
          sudo apt-get install -y fonts-ibm-plex
          fc-list | grep -i "ibm plex"

      - name: Install BIZ UD Gothic
        run: |
          sudo wget https://github.com/googlefonts/morisawa-biz-ud-gothic/releases/download/v1.05/BIZUDGothic-Regular.ttf -P /usr/share/fonts/truetype/
          sudo wget https://github.com/googlefonts/morisawa-biz-ud-gothic/releases/download/v1.05/BIZUDGothic-Bold.ttf -P /usr/share/fonts/truetype/
          sudo chmod 644 /usr/share/fonts/truetype/BIZUDGothic-*.ttf
          sudo fc-cache -fv
          # List installed fonts without failing if grep finds nothing
          fc-list | grep -i "biz" || true
          # Verify files exist
          ls -l /usr/share/fonts/truetype/BIZUDGothic-*.ttf

      - name: Install Playwright
        run: bunx playwright install --with-deps

      - name: build online book
        run: bun run build

      - name: build press-ready book
        run: bun run build:press-ready

      # PDFのアップロード
      - name: Upload PDF artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Artifacts
          path: ./*.pdf
          retention-days: 3

      # Playwrightレポートのアップロード
      - name: Upload Playwright report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 3
